#服务器端口
server:
  port: 8081
#数据库连接
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
#       content-type: text/html
    mode: LEGACYHTML5
  #    数据库连接
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/park?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 使用 druid 作为连接池  更多配置的说明可以参见 druid starter 中文文档 https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
        initialSize: 5
        # 最小连接池数量
        minIdle: 5
        # 最大连接池数量
        maxActive: 10
        # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
        maxWait: 60000
        # Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。
        timeBetweenEvictionRunsMillis: 60000
        # 连接保持空闲而不被驱逐的最小时间
        minEvictableIdleTimeMillis: 300000
        # 用来检测连接是否有效的sql 因数据库方言而差, 例如 oracle 应该写成 SELECT 1 FROM DUAL
        validationQuery: SELECT 1
        # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
        testWhileIdle: true
        # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        testOnBorrow: false
        # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        testOneRturn: false
        # 是否自动回收超时连接
        removeAbandoned: true
        # 超时时间(以秒数为单位)
        remove-abandoned-timeout: 180
        # druid 监控的配置 如果不使用 druid 的监控功能的话 以下配置就不是必须的
        # 本项目监控台访问地址: http://localhost:8080/druid/login.html
#        filter: stat,wall,logback
        filter:
#          sql监控
          wall:
            enabled: true
          stat:
            enabled: true
            log-slow-sql: true
            slow-sql-millis: 5000
            merge-sql: true
        # WebStatFilter用于采集web-jdbc关联监控的数据。
        web-stat-filter:
          # 是否开启 WebStatFilter 默认是true
          enabled: true
          # 需要拦截的url
          url-pattern: /*
          # 排除静态资源的请求
          exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
#          session监控
          session-stat-enable: true
          profile-enable: true
        # Druid内置提供了一个StatViewServlet用于展示Druid的统计信息。
        stat-view-servlet:
          #是否启用StatViewServlet 默认值true
          enabled: true
          # 需要拦截的url
          url-pattern: /druid/*
          # 允许清空统计数据
          reset-enable: false
          login-username: admin
          login-password: admin
        aop-patterns: com.qhit.*


  resources:
    static-locations: classpath:/static/,classpath:/static/lib/,classpath:/static/js/
  devtools:
    restart:
      enabled: true  #设置开启热部署
      exclude: templates/**
  #      additional-paths: src/main/java
  freemarker:
    cache: false #页面不加载缓存，修改即时生效
#    上传大小
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
  redis:
      database: 0
      host: localhost
      port: 6379
      password:
      timeout: 2000ms
#showSql
logging:
  level:
   com:
     qhit:
       parking:
         dao: debug
#mybatis连接
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
#debug: true